name: EA Nation Server deployment pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - ablondel
          - vps

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate .env
      env:
        QA_TESTERS_WHITELIST: ${{ secrets.QA_TESTERS_WHITELIST }}
        REBROADCASTER_API_KEY: ${{ secrets.REBROADCASTER_API_KEY }}
      run: |
        echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_NAME=ea-nation_db >> .env
        echo DB_PORT=5432 >> .env
        echo SERVER_IP=${{ secrets.SERVER_IP }} >> .env
        echo GPS_NAME=${{ secrets.GPS_NAME }} >> .env
        echo GPS_PWD=${{ secrets.GPS_PWD }} >> .env
        echo GPS_ADM_PWD=${{ secrets.GPS_ADM_PWD }} >> .env
        echo GPS_LOC=${{ secrets.GPS_LOC }} >> .env
        echo DNS_NAME=${{ secrets.DNS_NAME }} >> .env
        echo CONTENT_URL=${{ secrets.CONTENT_URL }} >> .env
        echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
        echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env
        echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env
        echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
        echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
        echo DISCORD_WEBHOOK_REPORTS=${{ secrets.DISCORD_WEBHOOK_REPORTS }} >> .env
        echo DISCORD_WEBHOOK_MONITORING=${{ secrets.DISCORD_WEBHOOK_MONITORING }} >> .env
        echo DISCORD_WEBHOOK_ALERTS=${{ secrets.DISCORD_WEBHOOK_ALERTS }} >> .env
        echo HTTP_TUNNEL_ENABLED=${{ secrets.HTTP_TUNNEL_ENABLED }} >> .env
        echo TCP_DEBUG_BUDDY=${{ secrets.TCP_DEBUG_BUDDY }} >> .env
        echo TCP_DEBUG_ENABLED=${{ secrets.TCP_DEBUG_ENABLED }} >> .env
        echo TCP_DEBUG_INLINE=${{ secrets.TCP_DEBUG_INLINE }} >> .env
        echo REBROADCASTER_ENABLED=${{ secrets.REBROADCASTER_ENABLED }} >> .env
        echo REBROADCASTER_URL=${{ secrets.REBROADCASTER_URL }} >> .env
        printf "QA_TESTERS_WHITELIST='%s'\n" "$QA_TESTERS_WHITELIST" >> .env
        printf "REBROADCASTER_API_KEY='%s'\n" "$REBROADCASTER_API_KEY" >> .env

    - name: Generate dnsmasq.conf
      run: |
        cat << EOF > dns-server/dnsmasq.conf
        no-resolv
        server=/ea.com/1.1.1.1
        server=/eahub.eu/1.1.1.1
        address=/pcburnout08.ea.com/${{ secrets.SERVER_IP }}
        address=/pcnfs05.ea.com/${{ secrets.SERVER_IP }}
        address=/pcnfs06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2afl06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2afl07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2burnout05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2burnout06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2coach06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2fifa06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2fifa07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2fifa08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2kok06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2madden06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2madden07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2madden08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2madden09.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2madden10.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2marvel06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2mm06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2mm07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2mvp06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2mvp07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nascar06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nascar07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nascar08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nascar09.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nba06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nba07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nba08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nbastreet05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa09.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ncaa10.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nflstreet05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nflstreet07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nfs04.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nfs05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nfs06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nhl06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nhl07.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2nhl08.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2sims04.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2ssx04.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2tw06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2uefa05.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2uefa06.ea.com/${{ secrets.SERVER_IP }}
        address=/ps2uefa07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspfifa06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspfifa07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspfifa08.ea.com/${{ secrets.SERVER_IP }}
        address=/pspfifa09.ea.com/${{ secrets.SERVER_IP }}
        address=/pspfifa10.ea.com/${{ secrets.SERVER_IP }}
        address=/pspkok06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmadden06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmadden07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmadden08.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmadden09.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmadden10.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmoh07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmoh08.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnba06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnba07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnba08.ea.com/${{ secrets.SERVER_IP }}
        address=/pspncaa07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnfs06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnfs07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnfs08.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnfs09.ea.com/${{ secrets.SERVER_IP }}
        address=/pspnhl07.ea.com/${{ secrets.SERVER_IP }}
        address=/psptw07.ea.com/${{ secrets.SERVER_IP }}
        address=/psptw08.ea.com/${{ secrets.SERVER_IP }}
        address=/psptw10.ea.com/${{ secrets.SERVER_IP }}
        address=/pspuefa06.ea.com/${{ secrets.SERVER_IP }}
        address=/pspuefa07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspworldcup10.ea.com/${{ secrets.SERVER_IP }}
        address=/wiimoh08.ea.com/${{ secrets.SERVER_IP }}
        address=/tos.ea.com/${{ secrets.SERVER_IP }}
        address=/msgconn.beta.ea.com/${{ secrets.SERVER_IP }}
        address=/naswii.nintendowifi.net/${{ secrets.SERVER_IP }}
        EOF
        DNAS_EU_IP="${{ secrets.DNAS_EU_IP }}"
        DNAS_JP_IP="${{ secrets.DNAS_JP_IP }}"
        DNAS_US_IP="${{ secrets.DNAS_US_IP }}"
        if [ -n "$DNAS_EU_IP" ]; then echo "address=/gate1.eu.dnas.playstation.org/$DNAS_EU_IP" >> dns-server/dnsmasq.conf; fi
        if [ -n "$DNAS_JP_IP" ]; then echo "address=/gate1.jp.dnas.playstation.org/$DNAS_JP_IP" >> dns-server/dnsmasq.conf; fi
        if [ -n "$DNAS_US_IP" ]; then echo "address=/gate1.us.dnas.playstation.org/$DNAS_US_IP" >> dns-server/dnsmasq.conf; fi

    - name: Clean remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: rm -rf /var/www/ea-nation-server/*

    - name: Copy project files to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/var/www/ea-nation-server"

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Run Docker Compose on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin
          cd /var/www/ea-nation-server
          source .env
          docker compose down --remove-orphans
          docker compose pull
          docker compose up --build -d
